CSU Team 8 Improvements
DPIclimate/broker pull request #55
Opened 2023-09-05 07:10 UTC by Heroj04

Implements the following improvements

- Kubernetes System Run Option
- MQTT Processors as plugins
- Monitoring via Prometheus/Grafana
- Management App Improvements for filtering unlinked physical devices

2023-10-03 04:19 UTC, dajtxx requested changes
Great work team, I can see a lot of effort has gone into this!

I know you're out of time because I have left things so late so don't feel you need to address many of the comments here.

I have tried to put some trivial changes in so you can honestly say you've modified things due to feedback.

I'll move onto the actual testing now. I can't get ports exposed using k8s nodeports so I'll work with docker compose until someone shows me where I'm going wrong.

2023-10-03 04:19 UTC, dajtxx commented on doc/mqtt_processor_plugins.md
> +If the raw message cannot be processed, an exception should be raised.
This is a bit ambiguous for the YDOC case where one incoming message generates multiple outgoing messages.

A more strict interface contract is required here but we can clean it up later.

2023-10-03 04:19 UTC, dajtxx commented on kubernetes.sh
> +if [ "$1" = "status" ]; then
Should mention this is k8s.md.

2023-10-03 04:19 UTC, dajtxx commented on kubernetes.sh
> +	kubectl get all --namespace=broker
Issue this command at the end of start to show what's now running.

2023-10-03 04:19 UTC, dajtxx commented on src/python/delivery/FRRED.py
> +messages_rejected_finish_flag = Counter('messages_rejected_finish_flag', 'Number of messages rejected due to the _finish flag being set')
Don't need messages_rejected_finish_flag in any of services.

2023-10-03 04:19 UTC, dajtxx commented on test.md
> +git test file
Delete this file?

2023-10-04 00:21 UTC, Heroj04 commented on kubernetes.sh
> +	kubectl get all --namespace=broker
This is addressed by CSU-ITC303-ITC309-2023-Team8/broker@2cdda21550849a61bb5bc7eefe4a90a699a43d26

2023-10-04 00:21 UTC, Heroj04 commented on kubernetes.sh
> +if [ "$1" = "status" ]; then
This is addressed by CSU-ITC303-ITC309-2023-Team8/broker@3b9ba8cae5cca7d85efe1a280f81cd3b2edfe332

2023-10-04 00:21 UTC, Heroj04 commented on doc/mqtt_processor_plugins.md
> +If the raw message cannot be processed, an exception should be raised.
I agree, but note as above I've tried to make this flexible, plugins can return as many messages as they want and can either include errors in the return or throw an error for the entire raw message.

2023-10-04 00:21 UTC, Heroj04 commented on src/python/mqtt_processors/plugins/Wombat.py
> +        'errors': []
If errors occur an error is thrown instead of returned

2023-10-04 00:21 UTC, Heroj04 commented on src/python/mqtt_processors/plugins/Wombat.py
> +        raise Exception(f'Physical device not found')
This is in the Wombat plugin which has a single device per message.
The YDOC plugin checks physical devices at [Line 208](https://github.com/DPIclimate/broker/pull/55/files/1acc09c58e8ccd48ceb7ce6ec4a5cd9bfc3cbf54#diff-0d2fa75f89dce23fcfc31559e8ffa58416fc59874fe534dc2e025b2bf43e157eR208) which is inside the devices loop

2023-10-04 00:21 UTC, Heroj04 commented on src/python/mqtt_processors/MQTTProcessors.py
> +  return lambda channel, method, properties, body: on_message(channel, method, properties, body, plugin_name)
Looks like there is `functools.partial` which is practically identical to using a lambda, however I personally think the syntax of the lambda is nicer.
From what I've read speed and tracebacks are very close.

2023-10-04 00:22 UTC, Heroj04 commented on src/python/mqtt_processors/MQTTProcessors.py
> +        channel.basic_ack(delivery_tag)
I just copied this from the way that Wombat and YDOC were already configured to work.
It probably is a good idea to set some upper limit on retries because typically a message error would be a persistent rather than some intermittent issue.

2023-10-04 00:22 UTC, Heroj04 commented on src/python/mqtt_processors/MQTTProcessors.py
> +    except Exception as e:
The processor actually handles both cases specifically for things such as YDOC.
Both cases are handled slightly differently but have the same outcome.
Plugins can throw errors but this will cause the entire raw message to fail and no messages are forwarded to the physical timeseries.
Plugins can also return the object which could include a mix of messages and errors, this is the case for YDOC where one sub message may succeed, and one may fail.
In both cases the raw message is acknowledged and errors are logged.

2023-10-04 00:22 UTC, Heroj04 commented on src/python/mqtt_processors/MQTTProcessors.py
> +        processed_message = plugin_modules[plugin_name].on_message(body, { 'channel': channel, 'method': method, 'properties': properties, 'body': body })
I did this so that the properties object would match the original Pika properties passed in case there was some specific function that needed the object in that format. Which I admit is unlikely and could be done in that specific case anyway.
Addressed in CSU-ITC303-ITC309-2023-Team8/broker@bff404a5223d691515f78bb6d255351e4dd9338c

2023-10-06 00:46 UTC, SamPixelYork commented on test.md
> +git test file
File removed [CSU-ITC303-ITC309-2023-Team8/broker@afbcc10](https://github.com/CSU-ITC303-ITC309-2023-Team8/broker/commit/afbcc10e61d322f681e9dc4894fccde9a95d5c29)

2023-10-06 00:49 UTC, SamPixelYork commented on src/python/delivery/FRRED.py
> +messages_rejected_finish_flag = Counter('messages_rejected_finish_flag', 'Number of messages rejected due to the _finish flag being set')
messages_rejected_finish_flag removed 755a0620daebc079cda0c03ece2dec2de847aa94

2023-10-06 00:49 UTC, SamPixelYork commented on src/python/logical_mapper/LogicalMapper.py
> +logical_mapper_exits_counter = Counter('logicalmapper_exits', 'Number of times the logical mapper script has exited')
Unwanted counters removed 5c81e380c96d11d40e8de67f8b6640e28312bfc1

2023-10-06 00:50 UTC, SamPixelYork commented on src/python/mqtt_processors/MQTTProcessors.py
> +            messages_processed_successfully.inc()
Moved counter to after RabbitMQ has been notified message processed f41926f69f809e0f0da4fef21c55c1f762d0193b

2023-10-10 06:16 UTC, SamPixelYork commented on src/python/mqtt_processors/plugins/Wombat.py
> +        wombat_messages_received.inc()
Corrected 3c9d7bd64bb025dd1ac902d3b54cfef1717a44cd

2023-10-31 00:41 UTC, merged